[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
